### ISSUE TITLE
Doesn't work in Linux

### ISSUE THREAD

**Issue by fedemp** [pranayrauthu/DevToolsFontChanger#3]
You have to add `.platform-linux .monospace, .platform-linux .source-code,` in line 10 of `devtools.js`.

BTW, great extension. :+1:

**Comment by pranayrauthu** [comment]
sure will do.

**Comment by fedemp** [comment]
```
     :host-context(.platform-linux) .monospace, 
     :host-context(.platform-linux) .source-code, 
```
line 5 and 6.
